### PR TITLE
#1618 synclab refactor format objects

### LINKED ISSUE #1618: SyncLab: Refactor Format objects
Would be a good idea to refactor the format objects to OOP rather than sticking to the current util classes + reflection style.
The code has been giving quite a bit of confusion thus far for code reviews.
Makes sense to do this before adding more SyncLab formats like #1213

### PR DESCRIPTION
**Pull request by alexfjw**
Fixes #1618 

Format objects now follow OOP, inheriting from an abstract Format class rather than act as static utility classes. This gives us type safety!

### CODE REVIEW

**Comment by alexfjw** [comment]
Also fixed a failing UT for copying placeholder pictures. 
Not sure why the failing UT missed our radar until now.

**Comment by alexfjw** [comment]
FTs & UTs work on 2016. 
(Except the sync artistic effect UT, which seems to be something specific to my system, tested to be manually working on 2016)

Note that sync artistic effect does not work on 2013. See #1644

**Comment by junkiattan** [comment]
Test works for PPT2013 and PPT2016

**Comment by leeyh20** [comment]
Yes the failing UT is "TestSetArtisticEffect".
Besides that, the other tests passed in PPT 2010.

**Comment by alexfjw** [comment]
For anyone giving a code review, here's a summary of the changes:
1) Format is an abstract class. All format classes now extend Format. 
2) Format also has it's equals & hashcode method modified. Format objects of the same class should be considered equal.
3) Fixing the failing placeholder picture test:
 PowerPointLabs/Test/UnitTest/PlaceHolderCopyTest.cs
PlaceHolder pictures were not copyable in the past. They are now and the test has been amended to show that.

**Comment by alexfjw** [comment]
@Skaty @initialshl @IanTeo 
Ready for a review, the added commit only includes only changes from the csproj file

**Pull request merged**
