### PR TITLE
#1343 Crop Lab: Provide PowerPoint's crop features in Crop Lab

### PR DESCRIPTION
**Pull request by junkiattan**
#1343 

hey @initialshl ,

1. I have included the default crop features for PowerPointLabs for PowerPoint 2010, 2013 and 2016
2. Ran tests to ensure no error with code

### CODE REVIEW

**Comment by initialshl** [comment]
Thanks. Can u provide a screenshot too?

**Comment by junkiattan** [comment]
@initialshl 

capture

**Comment by initialshl** [comment]
LGTM, just need peer reviews

**Comment by leeyh20** [comment]
I have tested this on PowerPoint 2016. Works like expected.

**Pull request merged**
