### PR TITLE
#26 Open SelectionPane after editting name

### LINKED ISSUE #26: Show selection panel after editing name
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on November 23, 2013 13:56:13_

After editing the name of an object, we can show the 'selection pane' automatically, if it is not already being displayed. 
This way, the user get a visual confirmation of the action result.

_Original issue: http://code.google.com/p/powerpointlabs/issues/detail?id=26_

### PR DESCRIPTION
**Pull request by ChesterSng**
Fixes #26

**Outline of Solution**

Open selection pane after user edits the name of a shape

### CODE REVIEW

**Comment by leeyh20** [comment]
Looks good but might need to test on all three versions of PPT to make sure the selection pane has the same idMso across the versions.

**Comment by ChesterSng** [comment]
Yeah I think it might have some issues with 2010.

**Comment by YuPeiHenry** [comment]
Tested and working on PPT2010.

**Comment by blewjy** [comment]
Hey @ChesterSng, this feature is working on PPT2016.

However, you may want to add this check so that the Selection Pane remains open if user were to edit the shape's name when the pane is already open
```c#
if (!this.GetApplication().CommandBars.GetPressedMso("SelectionPane"))
{
	this.GetApplication().CommandBars.ExecuteMso("SelectionPane");
}
```

**Comment by ChesterSng** [comment]
Thanks @blewjy! Changed it so it now works as expected

**Comment by ChesterSng** [comment]
@leeyh20 removed the extra files changed

**Pull request merged**
