### PR TITLE
#1209 improve text sync

### LINKED ISSUE #1209: Sync Lab: Improve Text Sync
Positioning 
See TextFrame.Orientation
- [ ] Add support for Text Orientation 

See TextFrame.TextRange.ParagraphFormat
- [ ] Add support for Alignment (Alignment)
- [ ] Add support for Line Spacing (LineRuleBefore/After/Within, SpaceBefore/After/Within)

Misc
- [ ] Add support for Strike through (not adding support, low value as user is unlikely to want all text to be striked through)

### PR DESCRIPTION
**Pull request by YuPeiHenry**
Fixes #1209

Ready for review (with tests). Tested and working on PPT2016. Does not support strike through as it is suggested as low value.

**Outline of Solution**
Text alignment: Used `TextFrame`'s Horizontal and Vertical Anchor.
Text orientation: Used `TextFrame`'s orientation.
Line spacing: Used `TextFrame.TextRange.ParagraphFormat`'s SpaceAfter, SpaceBefore and SpaceWithin.

### CODE REVIEW

**Comment by YuPeiHenry** [comment]
@ChesterSng turns out there was a bug in horizontal text alignment. I have fixed it, please look through when convenient.

**Comment by ChesterSng** [comment]
@YuPeiHenry Tested on PowerPoint 2016, working as expected now

**Comment by alexfjw** [comment]
Could someone test this on 2013 as well?
Unfortunately, SyncLab is one of labs which exhibits different behavior on different PPT versions.

**Comment by ChesterSng** [comment]
No problem on 2013 👍

**Comment by YuPeiHenry** [comment]
@alexfjw I have resolved the merge conflict.

**Pull request merged**
