### PR TITLE
#1577 Easy access to "Insert Shape" functionality for relevent Labs

### PR DESCRIPTION
**Pull request by junkiattan**
Resolves: #1577 
Relevant: #1575 

Added "Insert Shape" functionality for the following labs

1. Animation
2. Crop
3. Effects
4. Shapes
5. Zoom

to allow users to easily Insert shapes without needed to access tabs outside of "PowerPointLabs" tab

All FTs and UTs have passed

1, 2, 3, 5
insertshape1

4
insertshape2

### CODE REVIEW

**Comment by alexfjw** [comment]
LGTM, PPT2016. 

We automatically end up in the home ribbon after creating a shape though. Any idea if we can stick to the PowerPointLabs ribbon after creating a shape?

**Comment by alexfjw** [comment]
Works fine on PPT2013.

**Comment by Skaty** [comment]
@junkiattan resolve the conflict in `Ribbon1.xml` (preferably locally) before merging.

**Comment by leeyh20** [comment]
Tested on PPT 2010 and works as expected. @alexfjw I don't end up at the home ribbon after adding a shape in PPT 2010 though.

**Comment by alexfjw** [comment]
@leeyh20 That's interesting. Maybe we can continue this thread of convo on the new issue

**Comment by junkiattan** [comment]
@Skaty @initialshl 

Would appreciate your approval for this as soon as you can.

**Pull request merged**
