### PR TITLE
Allow custom formatting for generated captions #1029

### LINKED ISSUE #1029: Allow custom formatting for generated captions
Some users may want to use their own formatting for the generated captions e.g. left align

### PR DESCRIPTION
**Pull request by Dawnlord**
Fix #1029 

Can change
1. Size
2. Alignment
3. Color
4. Bold
5. Italic

### CODE REVIEW

**Comment by Dawnlord** [comment]
qq 20160711173138

**Comment by Dawnlord** [comment]
Still test and there seem to be some small bugs.

qq 20160712172006

**Comment by damithc** [comment]
The preview box should be at the bottom with the heading 'Preview:`, not in front of Bold and italic.

**Comment by Dawnlord** [comment]
qq 20160718161642

**Comment by damithc** [comment]
Back color --> Background color.
Does the dialog show the current style when loaded?

**Comment by Dawnlord** [comment]
Sure. It will show the current style.

**Comment by IanTeo** [comment]
Closing this stale PR

**Pull request closed without merging**
