### PR TITLE
Exception during installation #1295

### LINKED ISSUE #1295: Exception during installation
I tried to install alpha release from www.comp.nus.edu.sg/~pptlabs/download/alpha/PowerPointLabs.zip
but encountered an exception:
```
System.Deployment.Application.DeploymentDownloadException: Downloading http://www.comp.nus.edu.sg/~pptlabs/download/alpha/Application Files/PowerPointLabs_2017_3_31_1/Resources/TimerLab.png.deploy did not succeed. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
```
Since alpha has been merged into dev-release, the issue also affects dev version.

when publish a build, ensure the generated build doesn't have resources folder. resources shld be already included in the powerpointlabs.dll

to remove it, i believe to change from `content` to `resource` or `none`? https://github.com/PowerPointLabs/PowerPointLabs/blob/dev-release/PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj#L1699-L1702

### PR DESCRIPTION
**Pull request by IanTeo**
I hope this fixes #1295 as @kai33 described.
I haven't tested it as I am unsure how to test the installer.
I noticed SyncLab used None for one of the resources so I changed all of SyncLab's content to none, and TimerLab used Resouce, so I changed content to resource

### CODE REVIEW

**Comment by kai33** [comment]
Can you help verify it by:
1. [publish](https://msdn.microsoft.com/en-us/library/31kztyey.aspx) the project.
2. in the published folder, in which it has those powerpointlabs.dll things, verify that it doesn't have resources folder.
3. uninstall powerpointlabs add-in.
4. install powerpointlabs add-in from the published one. verify that the icons can be displayed properly

**Comment by IanTeo** [comment]
When I attempt to publish the app, they give me this screen

image

I am not sure what to do from here.. Am I supposed to just select the URL? Will the thing be uploaded onto alpha-release?

**Comment by kai33** [comment]
just proceed, it won't upload

**Comment by IanTeo** [comment]
Just tested. Icons can be displayed properly.
Also, there is no resources folder:

image

**Comment by kai33** [comment]
keep the good work :+1:

**Pull request merged**
