### PR TITLE
E-Learning Lab Version 4

### PR DESCRIPTION
**Pull request by LiXiaoooowei**
This PR adds IBM Watson voice integration and enhances existing features of e-learning lab

**PR Checklist**
- Add another voice option: IBM Watson voice
- Fix bug: eLL takes a long time to load when slide selection changes
- Enhance UI for audio settings page 
- Do not prompt user to sync if `No` is clicked

### CODE REVIEW

**Comment by LiXiaoooowei** [comment]
ELL slows down when animation pane is active. To testify that, close all presentations and start a new presentation. ELL loads in reasonable time if animation pane is not opened. Note that:

1.  Since PPT object model is shared across all presentations, opening animation pane on other PPT presentation will also slow down eLL in the current presentation. 
2. ELL still slows down even if animation pane is opened and closed later. I suspect that animation pane instance is still active even after it is closed later. 

PPT functionalities such as animation pane can possibly slow down eLL because eLL does not load on main thread. Given limited CPU resources, more threads can slow down each thread.

There exists some fixes but none of them are optimal:

1. We can load eLL on main thread. Note that this can slow down or even stuck PPT when we change slide selection quickly with eLL being opened.
2. We can add a loading spinner and advise user to wait patiently while loading.

@damithc What do you think?

**Comment by damithc** [comment]
We can add a spinner in either case.
We can use the main thread for eLL to see how bad the slowdown is. If it is noticeable, we can change it back.

**Comment by LiXiaoooowei** [comment]
Note to testers:

A valid IBM watson account is needed to generate Watson voice. To create a watson account, please follow the following procedures (adapted from [IBM cloud documentation](https://console.bluemix.net/docs/services/text-to-speech/getting-started.html#gettingStarted)):

1. Go to the [Text to Speech](https://console.bluemix.net/catalog/services/text-to-speech) page in the IBM cloud catalog.
2. Sign up for a free IBM cloud account or log in.
3. Click **Create** to create a text to speech instance
4. From the [IBM Cloud dashboard](https://console.bluemix.net/dashboard/apps), click on your text to speech instance to go to the text to speech service dashboard page.
5. On the **Manage** page, click **Show** to view your credentials.
6. Copy the `API key` and `URL` values. `API key` is needed to connect to the TTS instance. Instead of `URL` value, you simply need to provide the `region` info. `Region` refers to the place where your TTS instance is located.

**Comment by ChesterSng** [comment]
Hi @LiXiaoooowei, great job on integrating IBM Watson to eLearningLab!

Some minor issues that I found: 

**1.) Login form for IBM Watson voice can be put to the background**
i. Open ELL dropdown
ii. Open settings
iii. Click login for IBM Watson
iv. Click on anywhere outside of the form
Expected Behaviour: Error sound prompts user to enter details in form/close form first
Actual Behaviour: Form is sent to the background
*This does not happen for the Azure Cloud login form*

Will continue this list after further testing!

**Comment by blewjy** [comment]
Hi @LiXiaoooowei, just tested this on PPT2013. Couple of issues:

**1. Appeared as not logged in (in `Audio Preview Window`) after closing and reopening PPT**
*Steps to reproduce:*
a. Log in to IBM watson first, then close PPT and reopen.
b. Go straight to ELL and add an item, tick Voice, then open up the `Audio Preview Window`
c. You will see that under the IBM Watson, it appears that you are not logged in. However if you go to ELL settings, you will see that you are logged in. Then now you go back to the `Audio Preview Window` and the logged in status is then updated.

**2. "Speak" button (to preview voice) causes unhandled exception when PPT closes**
*Steps to reproduce*
a. Make sure you are logged in to IBM Watson or Azure (both have same error)
b. Add an item, tick Voice, and go to `Audio Preview Window`
c. Put some caption and select an IBM Watson voice or Azure voice, then click "Speak"
d. Close PPT, and you should get unhandled exception.
Note: This does not happen for `In-computer voice`.


**3. Able to spam click the "Speak" button for Azure and IBM Watson**
Similar to issue 2, for IBM Watson or Azure voice, I'm able to spam click the speak button very quickly and the audio will play back multiple times. This is not allowed for the In-computer voice. I think we should standardise this behaviour. Also, the number of times I click "Speak" is the number of unhandled exceptions I get in issue 2! You can't see it below, but I'm clicking on `Continue` (F5) in Visual Studio and more unhandled exceptions appear. GIF below:

spam-speak

**4. Able to select Azure/IBM Watson through voice preference even if not logged in**
I noticed that if i'm not logged into Azure/IBM Watson but I selected some of those as my voice preference, I am able to select them in the `Audio Preview Window`. The "Speak" button for them is actually disabled, but the radio button is not. If I were to select them as my voice and click OK, attempting to Sync will tell me that the voices can't be generated because I'm not authenticated, which is the correct behaviour. However, I was just thinking if it would be better to just disabled the radio button instead?

<hr>

There are also some errors which I encountered several times but unable to reproduce reliably, just thought I should list them out so that you can take note:

1. Sometimes when I try to click the "Speak" button very fast or click multiple times, the small little popup for the speaking of text does not dismiss after the audio preview is complete.

2. Voice preview was not working for all the Azure voices except `JessaRUS`, but seems to be working fine now...

**Comment by LiXiaoooowei** [comment]
Hi @ChesterSng Thanks for testing!

Fixed issue 1 and 4. 

For issue 2, progress bar can take a long time to appear because the system was validating Azure/Watson user account before syncing began. I removed this bottleneck process. Now progress bar should appear after minimal delays.

For issue 3, audio preview window is executing on another thread and currently I face problems to bring it to main UI thread. As a temporary fix, I closed any audio preview instance when self-explanation item is deleted from e-learning lab. This means that audio preview window will be closed as long as an item is deleted.

**Comment by LiXiaoooowei** [comment]
Hi @blewjy Thanks for testing!

Fixed issue 1 and 3. 

Note that I cannot exactly reproduce issue 2 because speak button seems to work fine for me. However, I believe that issue 2 and 3 are related and solving issue 3 should simultaneously solve issue 2 as well. Do let me know if otherwise.

> 2. Voice preview was not working for all the Azure voices except `JessaRUS`, but seems to be working fine now...

I believe this is related to issue 1. Fixing issue 1 should be able to fix this problem as well.

Regarding issue 4, please refer to a similar discussion [here](https://github.com/PowerPointLabs/PowerPointLabs/pull/1806#issuecomment-471389958). Since you bring it up again, let me discuss with Prof and I will open another issue to fix this problem if necessary.

**Comment by blewjy** [comment]
> Regarding issue 4, please refer to a similar discussion here. Since you bring it up again, let me discuss with Prof and I will open another issue to fix this problem if necessary.

Ahh yes, I vaguely remember experiencing something similar previously but couldn't find the link to the actual issue. Apologies for that! In that case if this is intended, then you can ignore that point!

**Comment by blewjy** [comment]
Hi @LiXiaoooowei, I tested again on PPT2013 and the bugs are fixed. Will continue to test and see if there are any other issues :)

**Comment by ChesterSng** [comment]
Hi @LiXiaoooowei, bugs are fixed. After further testing, could not find other bugs!

**Comment by leeyh20** [comment]
Will merge this for dev-release first, for testing. Do continue to discuss in future versions.

**Pull request merged**
