### PR TITLE
#1533 using Directive should follow OSS-Generics coding standard

### LINKED ISSUE #1533: using Directive should follow OSS-Generics coding standard
All C# files in the project should follow OSS-Generics C# coding standard: https://github.com/oss-generic/process/blob/master/codingStandards/CodingStandard-CSharp.md#layout

The using Directive should start with System namespace, followed by other namespaces sorted in ascending alphabetical order. Each different root namespace should be separated by a newline, for example:

```
using System;

using Microsoft.Dll;

using PowerPointLabs.ActionFramework;
using PowerPointLabs.Util;
```

### PR DESCRIPTION
**Pull request by yuhongherald**
Fixes #1533

Ready for review.

I thought that this can be recurring problem so I've decided to look for a macro to speed things up. To set up the macro environment, follow the instructions from the repo link below:

https://github.com/yuhongherald/VisualStudioDirectiveMacro/blob/master/README.adoc

Some other macros I found but are not used:
1. Some stackoverflow post, seemingly wrote in Visual Basic
https://stackoverflow.com/questions/283471/remove-unused-namespaces-across-a-whole-project-or-solution-at-once

Not used because: Can't find the Macros IDE plugin for Visual Basic macros

2. JetBrains ReSharper
http://www.jetbrains.com/resharper/

Not used because: 30-day trial, also not integrated into visual studio.

### CODE REVIEW

**Comment by junkiattan** [comment]
Hello @yuhongherald 

Thank you for helping to clean up the coding standards! It would be great if you also indicate which platforms (Powerpoint 2010/2013/2016) you have tested on and whether there were any issues with any versions.

Normally things should not go wrong with this types of PRs, but as you touched on a lot of files, it would be just let us know that the code works as before for each of the versions. It may also serve as a check for yourself, and as a future reference for more important PRs;)

**Comment by leeyh20** [comment]
@yuhongherald Do you or your friend have PPT 2013 to test this PR on?

**Comment by yuhongherald** [comment]
Nope sorry about that

**Comment by leeyh20** [comment]
Should be okay for merging and yes we could add it to dev documentation!

**Pull request merged**
