### PR TITLE
Pronounce feature should work for spelled out words #692

### LINKED ISSUE #692: Pronounce feature should work for spelled out words
e.g. 
[Pronounce: N U S] NUS [EndPronounce]

### PR DESCRIPTION
**Pull request by Dawnlord**
Fix #692

### CODE REVIEW

**Comment by damithc** [comment]
`[spell] NUS [/spell]`?

**Comment by Dawnlord** [comment]
@kai33 
Now I can support

[s]NUS[/s]
[s] NUS [/s]
[s]NUS [/s]
[s] NUS[/s]

**Comment by damithc** [comment]
The tag should be consistent with other tags. I prefer full word rather than one letter. Verbosity is useful as our users are not experts.

**Comment by Dawnlord** [comment]
I have update the tag as

[spell]NUS[/]
[spell] NUS [/]
[spell]NUS [/]
[spell] NUS[/]

The reason why I did not use `[/spell]` is that when using `Speak Selected Text` function, [/spell] will make some strange bugs.

**Comment by Dawnlord** [comment]
I think I also need to update the function of Narrations Lab.

**Comment by IanTeo** [comment]
Closing this stale PR

**Pull request closed without merging**
