### PR TITLE
Clean up ribbon

### PR DESCRIPTION
**Pull request by Dawnlord**
Rename funtions into xxx lab

### CODE REVIEW

**Comment by damithc** [comment]
Give a screenshot of the new ribbon?
Remember to get the code reviewed (first by a team member, then by Kai) before merging.

**Comment by Dawnlord** [comment]
OK. I will pay attention next time.

Here is the screenshot
qq 20160727173712

**Comment by damithc** [comment]
The previously section called `Labs` should now be called `More Labs` ?
I would like to merge `Spotlight Lab` with `Highlight Bullets Lab` and call it `HighLights Lab` but that can be done as a separate issue if you like.

**Comment by damithc** [comment]
Also, don't merge partially done (i.e. not releasable) work. This one is partially done because the documentation hasn't been updated to match the ribbon.

**Comment by Dawnlord** [comment]
Now working on merging `Spotlight Lab` with `Highlight Bullets Lab`.

Also, Kai told me if the changes are small and I am confident, I can merge it by myself. However, next time I will call fiona to review it first and then merge the PR. Sorry for merging it directly.

**Comment by damithc** [comment]
Yes, for minor changes you can review each other's code and get input from Kai for bigger changes only.

**Pull request merged**
