### PR TITLE
PasteLab: Core + Paste to Fill Slide

### PR DESCRIPTION
**Pull request by Skaty**
Paste to Fill Slide

Includes a common `PasteLabMain` class.

### CODE REVIEW

**Comment by Skaty** [comment]
@initialshl I am aware of that. However, there's no consistent way of filling the slide if the shape is rotated.

**Comment by initialshl** [comment]
> @initialshl I am aware of that. However, there's no consistent way of filling the slide if the shape is rotated.
I see, so its intended to work this way. Would be better if its at least positioned in the center of the slide though.

**Comment by Skaty** [comment]
@IanTeo Ok, will check that one out.

**Comment by Skaty** [comment]
@IanTeo @initialshl I've changed the routine such that it takes into account the visual dimensions. I found out that ResizeLab used PPShape, which is a neat abstraction.

**Comment by damithc** [comment]
> As for not being able to see it, I made it such that it only works if you select an empty item. It does make sense, as the action does not need an object. It can be added, but since PowerPoint has different context menus for different selections, it would involve duplicating the menu button.

We can go with this option in the initial version. We'll revisit the decision after dogfooding the feature for a while.

**Pull request merged**
