### PR TITLE
#1622: Correctly-Log-Failure-To-Sync-Font-Format

### LINKED ISSUE #1622: SyncLab: Verify logging conditions for Syncing
Some sync formats do not correctly log failure in syncing. 
Would be good to run through all logs in synclab again.

### PR DESCRIPTION
**Pull request by alexfjw**
fixes #1622 
Just a quick fix for an erroneous boolean value to properly log syncing of font format.

### CODE REVIEW

**Comment by alexfjw** [comment]
Don't think we really need to test this one.

**Comment by initialshl** [comment]
I suggest making an issue still. Also check that all other sync logs are correct too

**Comment by alexfjw** [comment]
I've already checked the other sync logs a min ago. Everything else seems fine though

**Comment by initialshl** [comment]
LGTM, mention the issue number in description and i will merge this PR

**Comment by alexfjw** [comment]
> LGTM, mention the issue number in description and i will merge this PR
Thanks for the quick review, have mentioned the issue number in the description.

**Pull request merged**
