### PR TITLE
support 'lock direction' feature #1000

### LINKED ISSUE #1000: support 'lock direction' feature
Similar to lock axis, but allows movement away/toward a reference object. 
If there is only one object, it will move in the rotated direction.

image

### PR DESCRIPTION
**Pull request by Dawnlord**
Fixes #1000

### CODE REVIEW

**Comment by vhazali** [comment]
Doesn't seem to work with one selected object

> If there is only one object, it will move in the rotated direction.

**Comment by Dawnlord** [comment]
It can work. When you select one object and click `lock direction`, then you can pull it to the left or right to make it rotate.

**Comment by vhazali** [comment]
Isn't it supposed to move in the rotated direction? 
I understood it as given just the arrow, it will still move in the direction shown in the image (without selecting the circle)
image

**Comment by Dawnlord** [comment]
However, in this situation, when we choose an object at the first time, how can we or users judge which object is the rotation center?

**Comment by vhazali** [comment]
Hmm, not really sure what you mean by rotation center. Are you asking how we can determine where the object is "pointing" to? Can take a look at the Snap Horizontal and Snap Vertical functions for that

**Comment by damithc** [comment]
Actually, the feature is meant to be used with a reference shape. However,
a good fallback for single object (i.e. no reference) is to lock the axis
based on its rotated direction.

**Comment by Dawnlord** [comment]
Therefore, when there is only one object, should it move or just rotate basing on its center axis? I did not understand rotated direction well.

**Comment by damithc** [comment]
Move, not rotate. This applies to objects that are rotated by some angle
(like the arrow in the screenshot). Instead of moving
horizontally/vertically relative to the slide, it will move relative to its
rotated direction.

**Comment by Dawnlord** [comment]
Ok, I will try to fix this function.

**Comment by Dawnlord** [comment]
@vhazali  How about now?

**Comment by vhazali** [comment]
Hi, sorry for the very long lack of response.

It's giving a quirky behavior as of now. Can I clarify what's the intended behavior for one object? 

For example, I'm testing it with these shapes
image
If i select the circle first then either or both of the arrows, they work perfectly (the arrows move in the direction they are pointing at, away and towards the circle depending on mouse movement)

However, if I select just the one arrow, the movements of the arrow are perpendicular to where they are pointing. i.e., for the right arrow, it moves as such:
image
and 
image

The same for the left arrow
image

I'm not sure if this is intended behavior. I guess it does lock the direction. If this is intended behavior then there's nothing wrong! :D

**Comment by vhazali** [comment]
Does it only work with arrows? I think another obvious object with direction might be the triangle but it doesn't seem to work with it.
image

Moving mouse to right:
image

**Comment by vhazali** [comment]
The Snap Vertical Icon seems to be distorted also?

**Comment by Dawnlord** [comment]
Actually, when just selecting one object, it is set to move in the rotated direction, but not the direction of the arrow. I will try to go through the code and check whether I can improve it.

**Comment by Dawnlord** [comment]
The bug of the text has been fixed. For the selected single object, it will only be locked by the rotated horizontal direction.
qq 20160823150019
qq 20160823150039
qq 20160823150055
qq 20160823150111

**Comment by Dawnlord** [comment]
@vhazali

**Comment by vhazali** [comment]
Cool! I think it works great now :D

**Comment by Dawnlord** [comment]
Document and Icon have been updated.

**Comment by vhazali** [comment]
@Dawnlord is there unit tests for this?

**Comment by Dawnlord** [comment]
The unit test for 'lock direction' is too complex. Now I still don't know how to write it. I will solve the conflict first.

**Comment by Dawnlord** [comment]
I think it may be similar to the test for 'Lock Axis', but I did not find the test for 'Lock Axis'.

**Comment by Dawnlord** [comment]
There are something wrong during my merging the conflict. Need time to solve it.

**Comment by Dawnlord** [comment]
Because of the error happening during solving the conflicts, I close this and rewrite one.

**Pull request closed without merging**
