### PR TITLE
StyleCop: Enable Access Modifier ordering rules #1081

### PR DESCRIPTION
**Pull request by Skaty**
This enables linting for the following rules in the C# Standard:
1. Sequence declaration within type groups are based on visibility in this order: `public, internal, protected internal, protected, private`.

Note that some files are not refactored, as this PR is more concerned on getting the rule enabled.

### CODE REVIEW

**Comment by Skaty** [comment]
@initialshl

See StyleCop Rule [SA1202](http://stylecop.soyuz5.com/sa1202.html).

Relevant PR: [oss-generic/process#59](https://github.com/oss-generic/process/pull/59)

**Comment by kai33** [comment]
FT result?

**Comment by Skaty** [comment]
@kai33 -- For me, FT & UT passes on 2015. Have to check with the rest for 2010 or 2013.

**Comment by Skaty** [comment]
@kai33: The relevant PR, oss-generic/process#59, has been merged. Can I check if this can be merged?

**Comment by kai33** [comment]
`Have to check with the rest for 2010 or 2013` any progress on this?

**Pull request merged**
