### PR TITLE
Rename Auto captions and auto narration #1050

### LINKED ISSUE #1050: Rename Auto captions and auto narration
Rename to Captions Lab and Narrations Lab
image
Need to update tutorial and user guide too.

### PR DESCRIPTION
**Pull request by Dawnlord**
Fix #1050

### CODE REVIEW

**Comment by damithc** [comment]
Check tutorial file and user docs too. Some screenshots/text may need updating.

**Comment by Dawnlord** [comment]
Is it in the PowerPointLabs-Website? I am reading it now.

**Comment by damithc** [comment]
Yes

**Comment by Dawnlord** [comment]
@kai33 May you help to merge it?

**Pull request merged**
