### PR TITLE
#1867 Adjust similarity tolerance for ZoomToArea test

### LINKED ISSUE #1867: ZoomToArea Test fail on some machines
As mentioned in PR [#1805](https://github.com/PowerPointLabs/PowerPointLabs/pull/1805), the `ZoomToArea` test fails on some machines even before the PR was made. 

We should adjust the similarity tolerance to account for the slightly different slides that different machines will generate.

### PR DESCRIPTION
**Pull request by ChesterSng**
Fixes #1867

1. Updated test slides
1. Adjusted similarity tolerance from default `0.95` to `0.89` to account for the slight difference in slides generated by `ZoomToArea` on different machines when there are multiple shapes to zoom into.

### CODE REVIEW

**Comment by LiXiaoooowei** [comment]
Tests passed on PPT2016. Code LGTM!

**Comment by leeyh20** [comment]
is it due to different resolutions on different machines?

**Comment by ChesterSng** [comment]
@leeyh20 unlikely to be because of resolution, because i adjusted the scaling on the same machine and it gives the same results

**Comment by blewjy** [comment]
[poslabeg.pptx](https://github.com/PowerPointLabs/PowerPointLabs/files/3088721/poslabeg.pptx)

**Comment by YuPeiHenry** [comment]
Test is passing on PPT 2010 and 2016.

**Pull request merged**
