### PR TITLE
Add preview for background highlight points

### LINKED ISSUE #2009: Highlight background does not preview animation
Currently in the highlight lab, only `Highlight Points` display an animation preview after adding the effect, but `Highlight Background` does not, even though they serve a similar function.

We should add a preview for `Highlight Background` as well.

### PR DESCRIPTION
**Pull request by ccyccyccy**
Fixes #2009 

### Outline of Solution
Fixed the issue by checking if animation is successfully added to the slide, and then playing the animation preview.

### CODE REVIEW

**Comment by iskandarzulkarnaien** [comment]
Tested to be working on 2016, have you run the test suite?

**Comment by ccyccyccy** [comment]
> 
> 
> Tested to be working on 2016, have you run the test suite?

Yep ran the test suite.

**Comment by iskandarzulkarnaien** [comment]
> 
> 
> > Tested to be working on 2016, have you run the test suite?
> 
> Yep ran the test suite.

Aiight nice work!

**Comment by xantho09** [comment]
Seems to be working on Office 365 (PPT 2019).

The change seems to preview all the animations in the slide (as opposed to only the animations added by Highlight Background). I realise the added lines are the same as those in `AddHighlightBulletsText()`. but is there a way to have only the newly added animations preview (e.g. when adding an animation via the standard Animations pane)?

**Comment by xantho09** [comment]
> _Is there a way to have only the newly added animations preview (e.g. when adding an animation via the standard Animations pane)?_

I suppose this can be made into another issue instead of trying to remedy it here. This PR looks good to me.

**Comment by ccyccyccy** [comment]
> > _Is there a way to have only the newly added animations preview (e.g. when adding an animation via the standard Animations pane)?_
> 
> I suppose this can be made into another issue instead of trying to remedy it here. This PR looks good to me.

Yeah I think so too. This behaviour is the same as the current one for point highlight

**Comment by ccyccyccy** [comment]
Sorry for the late reply. How should I change the branch name?
According to https://stackoverflow.com/questions/20007578/renaming-a-branch-while-on-pull-request, I should create a new pull request?

**Comment by YuPeiHenry** [comment]
Yeah it seems that the only way would be to open a new PR. You can reference this one for the previous reviews that are done.

**Comment by ccyccyccy** [comment]
Closing due to opening another PR for this.

**Pull request closed without merging**
