### PR TITLE
Help button redirecting to old docs site #1165

### LINKED ISSUE #1165: Help button redirecting to old docs site
The help button in the Ribbon currently redirects to the old docs html:

http://www.comp.nus.edu.sg/~pptlabs//docs.html

This should be the correct one:

http://www.comp.nus.edu.sg/~pptlabs/docs/

### PR DESCRIPTION
**Pull request by jamos-tay**
Fixes #1165.

Corrected docs link.
Also, 'Contact Us' is redirecting to
http://www.comp.nus.edu.sg/~pptlabs//contact.html
instead of
http://www.comp.nus.edu.sg/~pptlabs/contact.html
so changed to direct url.

### CODE REVIEW

**Comment by damithc** [comment]
> Why use www.comp.nus.edu.sg/~pptlabs instead of powerpointlabs.info?

Originally we were not sure where to host the website, so we gave the generic link. I guess better to use `www.comp.nus.edu.sg/~pptlabs` (faster)

**Comment by Skaty** [comment]
@damithc Hmm, sure.

**Comment by jamos-tay** [comment]
@Skaty Ah, the powerpointlabs.info link was adding an extra slash (e.g. ~pptlabs//contact.html instead of ~pptlabs/contact.html), probably due to the way the redirecting works.

**Comment by damithc** [comment]
> Ah, the powerpointlabs.info link was adding an extra slash (e.g. ~pptlabs//contact.html instead of ~pptlabs/contact.html), probably due to the way the redirecting works.

I removed the extra slash from the forwarding settings. Should take effect after a while.

**Comment by Skaty** [comment]
@jamos-tay It wasn't really affecting it that much though.

**Comment by IanTeo** [comment]
@Skaty I don't see a problem with this PR. After all, changing the link to use a direct URL is faster, and it does not affect anything else. Maybe you could approve the review, unless you have other reasons why we should use the old URL?

**Pull request merged**
