### PR TITLE
#1213 support for syncing softedge

### PR DESCRIPTION
**Pull request by alexfjw**
A part of #1213

### **Outline of Solution**
Adds support for Soft Edge effect in SyncLab.
The image preview modifies the actual SoftEdge effect to make it more visible.

### CODE REVIEW

**Comment by junkiattan** [comment]
Tested on 2013 and 2016. Syncing for Soft Edge works as expected.

In addition, provided test also works.

**Comment by junkiattan** [comment]
@leeyh20 Can you do a check on 2010 and update the labels if everything is good to go?

**Comment by leeyh20** [comment]
(as usual T___T) 

The options of "Size" is being overriden when I press Sync on the sync pane.

image

I set the "Size" to a very low value, but when I press Sync, it goes back to the default "Size".

**Comment by alexfjw** [comment]
@leeyh20 I can't seem to replicate your problem. I've tried using decimals for soft edge (30.23) in the included test file, and it seems to work fine.

**Comment by leeyh20** [comment]
Last bug!
Size is small but in the properties, it is overemphasised.

image

**Comment by initialshl** [comment]
Would be good to have at least 1 approving code review before i start to give my review

**Comment by alexfjw** [comment]
Merged dev-release again,
All tests are fine.

**Pull request merged**
