### PR TITLE
Support 'equalize angle' feature #1001

### LINKED ISSUE #1001: Support 'equalize angle' feature
For example, in the scenario below, equalize the angle between each arrow pair and the center of the circle
image

### PR DESCRIPTION
**Pull request by fionachang**
Fixes #1001

Need icon

### CODE REVIEW

**Comment by fionachang** [comment]
May not work properly if there are shapes that overlap the center of the reference shape.
It is not able to accurately determine whether there are shapes at a particular point (shapes that visually overlaps a point (seen from the fill/line) and not the bounding box).
Only certain shapes will show error messages while others continue to execute the feature.

**Comment by damithc** [comment]
What's the status of this?

**Comment by fionachang** [comment]
Waiting for merge

**Comment by vhazali** [comment]
Nice, seems to work perfectly as intended

**Pull request merged**
