### PR TITLE
#1581-SyncLab-Copying-SmartArt-gives-an-error

### PR DESCRIPTION
**Pull request by alexfjw**
Temporary fix for #1581.
Show a message when copying SmartArt, to mention that SmartArt is not supported by SyncLab.
This prevents an error that occurs when the system attempts to copy SmartArt.

### CODE REVIEW

**Comment by leeyh20** [comment]
LGTM! Tested on PPT 2010.

**Comment by alexfjw** [comment]
This won't be fixed any time soon I believe. Requires undiscovered workabouts. Thanks, I'll look into adding the FT.

**Comment by alexfjw** [comment]
Have added an FT for the message dialog. 
Also did some cleaning up for existing message dialog checks. (Hardcoded strings, unneeded imports)

**Comment by initialshl** [comment]
Can we rerun all tests for all ppt versions before i approve this pr?

**Comment by alexfjw** [comment]
Sure. Only test related files changed from that point but I'll just rerun the tests to be safe.

**Comment by junkiattan** [comment]
Have ran the test on PPT2013 and it works.

**Comment by leeyh20** [comment]
Runs on PPT2010 and it works.

**Pull request merged**
