### PR TITLE
PasteAndReplace: Ensure that it works for items in group

### LINKED ISSUE #1269: 'Replace with clipboard' should be available for all objects
Currently, the option does not appear for some objects.
v2017.3.31.1

image

### LINKED ISSUE #1270: Error while trying to replace shape in a group
I was trying to replace the yellow shape with the kids picture. The kid's picture got added to the group instead of replacing the yellow shape.

image

### PR DESCRIPTION
**Pull request by Skaty**
Fixes #1270

### CODE REVIEW

**Comment by initialshl** [comment]
I got an uncaught exception when I try to "Paste Into One Group" when two shapes are selected.



Also, what's the difference between "Merge into one group" and just using PowerPoint's "Group"?

**Comment by Skaty** [comment]
@initialshl
PPT's group does not preserve animations

**Comment by initialshl** [comment]
@Skaty 
I see, so it keeps the first shape's animation for the group.

Btw i got another exception, this time by "Paste into group" after selecting two textboxes (the blue shape appeared with the exception)

**Comment by Skaty** [comment]
@initialshl This PR is for "Paste and Replace" not Paste into group. Please raise an issue for that. :)

**Comment by initialshl** [comment]
@Skaty 
Okay I opened an issue for 'Paste Into Group'. But this PR doesnt fix the referenced issue though.
Issue 1269: 'Replace with clipboard' should be available for all objects

'Replace with clipboard' is still not available for groups and pictures.

**Comment by initialshl** [comment]
Ok, this fixes issue 1270 (after edit).

**Pull request merged**
