### PR TITLE
#2017 replace with clipboard only keeps first and last animation and has undo exception

### LINKED ISSUE #2017: ReplaceWithClipboard only preserves first and last animation, exception thrown on undo and replace again
As in title.

Steps to reproduce:

1. Create any shape, apply > 2 animations
2. Copy any other shape
3. Use ReplaceWithClipboard on first shape. Successful, however only first and last added animation remain
4. Ctrl-Z to undo. Successful, however duplicate animations have been added to shape 1. Some animations are also added to "Unnamed" shape.
5. Use ReplaceWithClipboard on first shape again. Exception thrown.

### PR DESCRIPTION
**Pull request by iskandarzulkarnaien**
Fixes #2017 

Solution Outline:
- Modified `PowerPointSlide#TransferAnimation` to copy all animations instead just first and last
- Add undo entry for `ReplaceWithClipboardActionHandler` and remove animations from source shape (shape being replaced) before deleting it.

Steps to reproduce issue on dev-release:
   - Create any shape, apply > 2 animations
   - Copy any other shape
   - Use ReplaceWithClipboard on first shape. Successful, however only first and last added animation remain
  - Ctrl-Z to undo. Successful, however duplicate animations have been added to shape 1. Some animations are also added to "Unnamed" shape.
   - Use ReplaceWithClipboard on first shape again. Exception thrown.

### CODE REVIEW

**Comment by xantho09** [comment]
Will test locally after merge conflicts are resolved.

Issue is reproducible in `dev-release` in PPT 2019 (365), though specifics as to which animations remain seem to vary.

To name an example:
1. Create a Rectangle and apply the following animations in order:
   1. Entrance: Appear
   1. Entrance: Swivel
   1. Emphasis: Desaturate
   1. Emphasis: Transparency
   1. Exit: Shrink & Turn
1. Perform steps 2 and 3 as mentioned in original reproduction steps.
1. The remaining animations on Shape 1 are:
   1. Entrance: Appear
   1. Entrance: Grow & Turn

**Comment by iskandarzulkarnaien** [comment]
@ccyccyccy i fixed the issue where exit effects are changed to entry effects, could you re-review?

**Comment by ccyccyccy** [comment]
> 
> 
> @ccyccyccy i fixed the issue where exit effects are changed to entry effects, could you re-review?

Seems good. Exit effects are preserved upon undoing, and it no longer crashes with exception.

However, if you undo again, all animations are duplicated. Might want to fix it in another PR?

**Comment by iskandarzulkarnaien** [comment]
@ccyccyccy seems like the undo issue is not present on 2013.

@YuPeiHenry could you help to check whether the issue is present on 2010?

**Comment by YuPeiHenry** [comment]
The undo issue does not affect 2010.

**Comment by iskandarzulkarnaien** [comment]
Alright, thanks guys! I've created issue #2024 to track the undo issue for 2016.

**Pull request merged**
