### PR TITLE
#1596 Fix error for adding captions without notes in PPT 2010

### LINKED ISSUE #1596: Captions Lab: Error in PPT 2010 when having no notes and then generating captions
Occurs in PPT 2010, not sure about other versions.
```
System.ArgumentException
Value does not fall within the expected range.
Stack Trace:
   at Microsoft.Office.Core._CommandBars.ExecuteMso(String idMso)
   at PowerPointLabs.CaptionsLab.NotesToCaptions.ShowNotesPane() in D:\Git Projects\PPLABS\PowerPointLabs\PowerPointLabs\CaptionsLab\NotesToCaptions.cs:line 183
   at PowerPointLabs.CaptionsLab.NotesToCaptions.EmbedCaptionsOnSlides(List`1 slides) in D:\Git Projects\PPLABS\PowerPointLabs\PowerPointLabs\CaptionsLab\NotesToCaptions.cs:line 42
   at PowerPointLabs.CaptionsLab.NotesToCaptions.EmbedCaptionsOnSelectedSlides() in D:\Git Projects\PPLABS\PowerPointLabs\PowerPointLabs\CaptionsLab\NotesToCaptions.cs:line 29
   at PowerPointLabs.ActionFramework.CaptionsLab.AddCaptionsActionHandler.ExecuteAction(String ribbonId) in D:\Git Projects\PPLABS\PowerPointLabs\PowerPointLabs\ActionFramework\CaptionsLab\AddCaptions\AddCaptionsActionHandler.cs:line 27
   at PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute(String ribbonId) in D:\Git Projects\PPLABS\PowerPointLabs\PowerPointLabs\ActionFramework\Common\Interface\ActionHandler.cs:line 14
```
It is because of this line `Globals.ThisAddIn.Application.CommandBars.ExecuteMso("ShowNotes");`

According to the website http://youpresent.co.uk/idmso-control-list-powerpoint-2013-2010/, this idMso might not exist in PPT 2010.

### PR DESCRIPTION
**Pull request by leeyh20**
Fixes #1596 
ExecuteMso("Show Notes") should only be done in versions not 2010.

Also refactored other similar version checks to an API function in ThisAddIn.

### CODE REVIEW

**Comment by alexfjw** [comment]
LGTM, works fine on 2013 as well.

**Comment by junkiattan** [comment]
@leeyh20 

Reviewed the code and tested on PPT2016. LGTM

**Comment by alexfjw** [comment]
ExecuteMso("Show Notes") is only used when the slide has no captions, as a shortcut for the user to enter some notes. Doesn't affect main usage

**Comment by initialshl** [comment]
So nothing happens in 2010 when generate captions is clicked? Or is it greyed out or has error message?

**Comment by leeyh20** [comment]
@initialshl  Currently, there is an error message shown:

image

**Comment by initialshl** [comment]
LGTM

**Pull request merged**
