### PR TITLE
#1836 Add Unit Tests for TooltipsLab

### LINKED ISSUE #1836: Add Unit Tests for TooltipsLab
Since the functionalities of TooltipsLab is finalised, we can start adding unit tests to TooltipsLab.

### PR DESCRIPTION
**Pull request by YuPeiHenry**
Ready for Review.
Fixes #1836

Completes the remaining tests continuing from @blewjy PR.
Note: AddTriggerAnimation parameters are changed to facilitate testing. Behavior remains the same.

### CODE REVIEW

**Comment by LiXiaoooowei** [comment]
Run tooltips lab UTs on PPT2016 and all passed.

**Comment by leeyh20** [comment]
Should mention in your PR description that AddTriggerAnimation parameters are changed?

**Comment by ChesterSng** [comment]
Hi @YuPeiHenry, suggest that you can add one more test case with more shapes, e.g. 10 shapes

**Comment by YuPeiHenry** [comment]
> Should mention in your PR description that AddTriggerAnimation parameters are changed? Not only tests are added, but the method has changed.

Ok. Updated the description.

**Pull request merged**
