### PR TITLE
Add 'flip' support #1007

### LINKED ISSUE #1007: Add 'flip' support
For completeness sake, we can also support the default flip features that come with PowerPoint

### PR DESCRIPTION
**Pull request by Dawnlord**
Fixes #1007 

Use keyboard `Ctrl` to change the function Icon and functions.

### CODE REVIEW

**Comment by Dawnlord** [comment]
@kai33 @vhazali Who can help review this?

**Comment by vhazali** [comment]
I think the functionality wise it's fine, however the Ctrl button is supposed to change the icon also right?

This doesn't happen unless I click on the Position Lab's sidebar

i.e. if I click on the object, then I ctrl+click, it does the vertical flipping, but the icon and tooltip says vertical flipping. But if after clicking on the object, I click on the sidebar first, when I hold ctrl, then the icon changes to the vertical one.

I think this is a tad confusing for users?

**Comment by Dawnlord** [comment]
I have improve the function. This time, if you move your mouse into the position lab pane, the icon will be changed by `ctrl`. I think now it would not confuse the users.

**Comment by Dawnlord** [comment]
@vhazali  May you have a check?

**Comment by vhazali** [comment]
Nice nice, I think the functionality is good.

Just, one thing to consider though. While I think using the `Ctrl` key is nice and all, I think it won't be intuitive for the user initially? And It's kind of not in line with how we implement the rest of PPTLab's features.

@damithc What do you think of the `Ctrl` button? If you're fine with it then I think we can go ahead with the merging

**Comment by vhazali** [comment]
Almost forgot about this but, the other functions in Positions Lab and Resize Lab has a preview function if you hold `Shift` and hover over the icon. 

I think we would eventually want this function too? Not sure if it's better to merge first then add the preview or vice versa

**Comment by Dawnlord** [comment]
There are still some trouble in the `preview` function for `flip`, I am still working on it and try to complete it today.

**Comment by Dawnlord** [comment]
The conflict has been solved and the preview has been completed. However, the `ctrl` may make the users confusing when using preview. It still needs to be improved. The basic function is fine now.

**Comment by Dawnlord** [comment]
@vhazali  I have updated the `flip` function and add `preview` for it.

**Comment by vhazali** [comment]
The icon switching has a bug.
If mouse is at the side panel, pressing `ctrl` will switch the icon (between vertical and horizontal)
If I hold `ctrl + shift`, let go of `shift`, then from now on pressing `shift` will switch the icon (while holding onto `ctrl`)
This does **not** affect the actual functionality, just the icon is wrong.

**Comment by vhazali** [comment]
The keys has a bug.
Mouse is at side panel.
When I preview any of the other function, by pressing `ctrl` will remove the preview. I think this is related / the same bug as the previous one

**Comment by Dawnlord** [comment]
I will check it and try to think out a new way to release the changing of functions.

**Comment by Dawnlord** [comment]
@vhazali  I change the way of `ctrl` working. When you press `ctrl` one time. It is changed to the other icon and function. When you press `ctrl` again, it will be changed to the original icon and function.

**Pull request merged**
