### PR TITLE
Redirect in README could be improved #1188

### LINKED ISSUE #1188: Redirect in README could be improved
This is with reference to this link in readme.md under the Setup section:

image

When clicked, it redirects to [this link](https://github.com/PowerPointLabs/PowerPointLabs-Website/blob/master/vsto-redirect.html), which is a html file within github where the user is asked to extract a URL from:

image

This seems pretty unelegant. A better idea would be to link to the same html file hosted on the server, which redirects them to the correct URL directly:

http://powerpointlabs.info/vsto-redirect.html

### PR DESCRIPTION
**Pull request by jamos-tay**
Fixes #1188.

Changed link in readme from [this](https://github.com/PowerPointLabs/PowerPointLabs-Website/blob/master/vsto-redirect.html) to [this](http://powerpointlabs.info/vsto-redirect.html).

### CODE REVIEW

**Comment by Kenneth-LJS** [comment]
LGTM

**Comment by acjh** [comment]
1. The sentence no longer fits the new link.
1. Is there a purpose for clicking on a link to a file to be immediately redirected? Why not link directly?

**Comment by jamos-tay** [comment]
@acjh 
1. Thanks for pointing this out, I have reworded the sentence to make it more applicable.
2. I think this is safer since the vsto-redirect may be accessible from elsewhere, and also we might want to change the link to download in future if Microsoft's URL changes. In this case, we only need to change the link in the vsto-redirect file instead of both the vsto-redirect and the readme.

**Comment by Skaty** [comment]
I think linking to our website from this repository is not really a good choice. It would be better if this repository does not depend on the website.

Also, @jamos-tay, your second point doesn't really hold, as we can update the README when it is needed.

**Comment by jamos-tay** [comment]
@Skaty Fair enough, you could update both, but I think this violates DRY. It makes sense that a string const such as a URL should only be stored in one location, and have everything reference it rather than having it stored in multiple places. Sure, you and I will know to update both, but future programmers who need to change the link might just change it in one place and not realize that another link needs to be changed.

**Comment by Skaty** [comment]
@jamos-tay Makes sense, in a way.

**Comment by kai33** [comment]
the history of vsto-redirect:
few years ago, MS has a convention to update VSTO for PowerPoint quarterly or at least a few times yearly. every time when it updates, the previous link won't work anymore (404). that in fact results in: we'll need to modify the link in powerpoint installer and re-publish it; the installer downloaded previously by users will have a broken link, which may be misleading to them. so i added this vsto-redirect thing, and let the CI guard it. then no more new release required, and its link should never be broken

**Comment by jamos-tay** [comment]
@kai33 Ah, so is there anything else I should do for this PR?

**Pull request merged**
